/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tefunayama' at '15/05/22 14:14' with Gradle 2.4
 *
 * @author tefunayama, @date 15/05/22 14:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
